name: matrix_flow
on:
  workflow_dispatch:

jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        fruit:
          - name: apple
            quantity: 1
          - name: orange
            quantity: 2
          - name: pear
            quantity: 1
        os_version: [macos-latest, ubuntu-latest]
        node_version: [12, 14, 16]

    name: My first job
    runs-on: ${{ matrix.os_version }}
    steps:
      - run: echo ${{ matrix.fruit.name }} >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}
